export const districts = [
  {
    city: "Varna",
    lat: "43.2114",
    lng: "27.9111",
    country: "Bulgaria",
    iso2: "BG",
    admin_name: "Varna",
    capital: "admin",
    population: "369162",
    population_proper: "369162",
    region: "Burgas",
  },
  {
    city: "Plovdiv",
    lat: "42.1433",
    lng: "24.7489",
    country: "Bulgaria",
    iso2: "BG",
    admin_name: "Plovdiv",
    capital: "admin",
    population: "340494",
    population_proper: "297685",
    region: "Burgas",
  },
  {
    city: "Burgas",
    lat: "42.5000",
    lng: "27.4667",
    country: "Bulgaria",
    iso2: "BG",
    admin_name: "Burgas",
    capital: "admin",
    population: "226868",
    population_proper: "226868",
    region: "Burgas",
  },
  {
    city: "Ruse",
    lat: "43.8445",
    lng: "25.9539",
    country: "Bulgaria",
    iso2: "BG",
    admin_name: "Ruse",
    capital: "admin",
    population: "163712",
    population_proper: "163712",
    region: "Burgas",
  },
  {
    city: "Stara Zagora",
    lat: "42.4257",
    lng: "25.6346",
    country: "Bulgaria",
    iso2: "BG",
    admin_name: "Stara Zagora",
    capital: "admin",
    population: "158668",
    population_proper: "158668",
    region: "Burgas",
  },
  {
    city: "Pleven",
    lat: "43.4132",
    lng: "24.6169",
    country: "Bulgaria",
    iso2: "BG",
    admin_name: "Pleven",
    capital: "admin",
    population: "123588",
    population_proper: "123588",
    region: "Burgas",
  },
  {
    city: "Sliven",
    lat: "42.6781",
    lng: "26.3260",
    country: "Bulgaria",
    iso2: "BG",
    admin_name: "Sliven",
    capital: "admin",
    population: "107570",
    population_proper: "107570",
    region: "Burgas",
  },
  {
    city: "Dobrich",
    lat: "43.5667",
    lng: "27.8333",
    country: "Bulgaria",
    iso2: "BG",
    admin_name: "Dobrich",
    capital: "admin",
    population: "104530",
    population_proper: "104530",
    region: "Burgas",
  },
  {
    city: "Shumen",
    lat: "43.2700",
    lng: "26.9244",
    country: "Bulgaria",
    iso2: "BG",
    admin_name: "Shumen",
    capital: "admin",
    population: "97719",
    population_proper: "97719",
    region: "Burgas",
  },
  {
    city: "Haskovo",
    lat: "41.9346",
    lng: "25.5556",
    country: "Bulgaria",
    iso2: "BG",
    admin_name: "Haskovo",
    capital: "admin",
    population: "93821",
    population_proper: "93821",
    region: "Burgas",
  },
  {
    city: "Pazardzhik",
    lat: "42.1892",
    lng: "24.3317",
    country: "Bulgaria",
    iso2: "BG",
    admin_name: "Pazardzhik",
    capital: "admin",
    population: "84619",
    population_proper: "84619",
    region: "Burgas",
  },
  {
    city: "Yambol",
    lat: "42.4824",
    lng: "26.5038",
    country: "Bulgaria",
    iso2: "BG",
    admin_name: "Yambol",
    capital: "admin",
    population: "84232",
    population_proper: "84232",
    region: "Sofia",
  },
  {
    city: "Pernik",
    lat: "42.6097",
    lng: "23.0308",
    country: "Bulgaria",
    iso2: "BG",
    admin_name: "Pernik",
    capital: "admin",
    population: "83973",
    population_proper: "83973",
    region: "Sofia",
  },
  {
    city: "Blagoevgrad",
    lat: "42.0119",
    lng: "23.0897",
    country: "Bulgaria",
    iso2: "BG",
    admin_name: "Blagoevgrad",
    capital: "admin",
    population: "82606",
    population_proper: "82606",
    region: "Sofia",
  },
  {
    city: "Veliko Tarnovo",
    lat: "43.0822",
    lng: "25.6317",
    country: "Bulgaria",
    iso2: "BG",
    admin_name: "Veliko Tarnovo",
    capital: "admin",
    population: "72207",
    population_proper: "72207",
    region: "Sofia",
  },
  {
    city: "Vratsa",
    lat: "43.2121",
    lng: "23.5444",
    country: "Bulgaria",
    iso2: "BG",
    admin_name: "Vratsa",
    capital: "admin",
    population: "69493",
    population_proper: "69493",
    region: "Sofia",
  },
  {
    city: "Kardzhali",
    lat: "41.6400",
    lng: "25.3708",
    country: "Bulgaria",
    iso2: "BG",
    admin_name: "Kardzhali",
    capital: "admin",
    population: "66128",
    population_proper: "66128",
    region: "Sofia",
  },
  {
    city: "Kyustendil",
    lat: "42.2811",
    lng: "22.6889",
    country: "Bulgaria",
    iso2: "BG",
    admin_name: "Kyustendil",
    capital: "admin",
    population: "63359",
    population_proper: "63359",
    region: "Sofia",
  },
  {
    city: "Gabrovo",
    lat: "42.8711",
    lng: "25.3150",
    country: "Bulgaria",
    iso2: "BG",
    admin_name: "Gabrovo",
    capital: "admin",
    population: "62938",
    population_proper: "62938",
    region: "Sofia",
  },
  {
    city: "Asenovgrad",
    lat: "42.0082",
    lng: "24.8773",
    country: "Bulgaria",
    iso2: "BG",
    admin_name: "Plovdiv",
    capital: "",
    population: "59793",
    population_proper: "59793",
    region: "Sofia",
  },
  {
    city: "Vidin",
    lat: "43.9887",
    lng: "22.8741",
    country: "Bulgaria",
    iso2: "BG",
    admin_name: "Vidin",
    capital: "admin",
    population: "58018",
    population_proper: "58018",
    region: "Sofia",
  },
  {
    city: "Kazanlak",
    lat: "42.6167",
    lng: "25.4000",
    country: "Bulgaria",
    iso2: "BG",
    admin_name: "Stara Zagora",
    capital: "",
    population: "56047",
    population_proper: "56047",
    region: "Sofia",
  },
  {
    city: "Montana",
    lat: "43.4055",
    lng: "23.2242",
    country: "Bulgaria",
    iso2: "BG",
    admin_name: "Montana",
    capital: "admin",
    population: "49597",
    population_proper: "49597",
    region: "Sofia",
  },
];
